#!/bin/sh

set -e

if [ "$1" = configure ]; then
    # This is idempotent, so it's OK to do every time. The system bus' init
    # script does this anyway, but you also have to do this before a session
    # bus will work on non-systemd systems, so we do this here for the
    # benefit of people starting a temporary session bus in a chroot.
    mkdir -p "${DPKG_ROOT:-/}var/lib/dbus"
    dbus-uuidgen --ensure="${DPKG_ROOT:-/}var/lib/dbus/machine-id"
fi

#DEBHELPER#

exit 0
